version = 1

exclude_patterns = [
  "src/lib/**",
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "vitest",
    "jest"
  ]
  dialect = "flow"
  style_guide = "standard"
